image: erpukraine/pipelines:default-image-2

pipelines:
  default:
    - step:
        name: Unit Tests
        script:
          - ./tests.sh
        services:
          - postgres
          - docker
  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: production
          services:
            - docker
          script:
            - ./deploy-erpu-saas.sh production
    staging:
      - step:
          name: Deploy to Staging
          deployment: staging
          services:
            - docker
          script:
            - ./deploy-erpu-saas.sh staging1
definitions:
  services:
    postgres:
      image: postgres:16.4
      environment:
        POSTGRES_PASSWORD: odoo
        POSTGRES_USER: odoo
