- hosts: all
  remote_user: bohdan
  become: true

  tasks:
    - name: Set Image name
      set_fact:
        image: "erpukraine/custom:{{ BITBUCKET_REPO_SLUG }}-{{ O_MAJOR }}.0-{{ BITBUCKET_BUILD_NUMBER }}"

    - name: Set Production Values
      set_fact:
        volume_path: "/swarm/gv1/{{ BITBUCKET_REPO_SLUG }}{{ O_MAJOR }}-data"
        service: "{{ BITBUCKET_REPO_SLUG }}{{ O_MAJOR }}"
        replicas: "{{ WORKERS_COUNT | default('1') | int }}"
        # service_underscored: "{{ service | replace('-', '_') }}"
      when: WITH_TEST_DB is undefined or WITH_TEST_DB != "yes"

    - name: Set Staging Values
      set_fact:
        volume_path: "/swarm/gv1/{{ BITBUCKET_REPO_SLUG }}{{ O_MAJOR }}-staging-data"
        service: "{{ BITBUCKET_REPO_SLUG }}-staging{{ O_MAJOR }}"
        replicas: 1
        domain: ""
      when: WITH_TEST_DB is defined and WITH_TEST_DB == "yes"

    - name: Display variables
      debug:
        msg: "volume_path: {{ volume_path }}, service: {{ service }}, replicas: {{ replicas }}, WORKERS_COUNT: {{ WORKERS_COUNT }}"

    - name: Ensure Odoo volume
      file:
        path: "{{ volume_path }}"
        state: directory
        owner: "101"
        group: "101"
        mode: 0755

    - name: Log into DockerHub
      docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"

    - name: Setup common labels
      set_fact:
        common_labels:
          traefik.enable: "true"
          erpu.odoo: "{{ O_MAJOR }}"

    - name: Setup common traefik v1 labels
      set_fact:
        traefik_v1_labels:
          traefik.docker.network: "erpunet"
          traefik.frontend.passHostHeader: "true"
          traefik.backend.loadbalancer.swarm: "true"
          traefik.backend.loadbalancer.method: "drr"
          traefik.frontend.headers.SSLProxyHeaders: "X-Forwarded-Proto:https"

    - name: Setup staging traefik v1 labels
      set_fact:
        staging_traefik_v1_labels:
          traefik.webtest.frontend.rule: "Host:{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua"
          traefik.webtest.frontend.redirect.regex: "^(https://{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua/website/tests|https://{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua/website/info|https://{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua/web/database/[^l].*)"
          traefik.webtest.frontend.redirect.replacement: "https://{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua"
          traefik.webtest.port: "8069"
          traefik.webtest.frontend.entryPoints: "https"
      when: WITH_TEST_DB is defined and WITH_TEST_DB == "yes"

    - name: Setup staging traefik v2 labels
      set_fact:
        staging_traefik_v2_labels:
          - key: "traefik.http.middlewares.{{ service }}-webtest-redirect.redirectregex.regex"
            value: "^(https://{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua/website/tests|https://{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua/website/info|https://{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua/web/database/[^l].*)"
          - key: "traefik.http.middlewares.{{ service }}-webtest-redirect.redirectregex.replacement"
            value: "https://{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua"
          - key: "traefik.http.routers.{{ service }}-webtest.rule"
            value: "Host(`{{ BITBUCKET_REPO_SLUG }}-staging.erp.co.ua`)"
          - key: "traefik.http.routers.{{ service }}-webtest.middlewares"
            value: "{{ service }}-webtest-redirect@docker,fw-proto@file,gzip@file"
          - key: "traefik.http.routers.{{ service }}-webtest.service"
            value: "{{ service }}-webtest"
          - key: "traefik.http.routers.{{ service }}-webtest.entryPoints"
            value: "websecure"
          - key: "traefik.http.services.{{ service }}-webtest.loadbalancer.server.port"
            value: "8069"
      when: WITH_TEST_DB is defined and WITH_TEST_DB == "yes"

    - name: Setup production traefik v1 labels
      set_fact:
        production_traefik_v1_labels:
          traefik.web.frontend.rule: "Host:{{ BITBUCKET_REPO_SLUG }}.erp.co.ua"
          traefik.web.frontend.redirect.regex: "^(https://{{ BITBUCKET_REPO_SLUG }}.erp.co.ua/website/tests|https://{{ BITBUCKET_REPO_SLUG }}.erp.co.ua/website/info|https://{{ BITBUCKET_REPO_SLUG }}.erp.co.ua/web/database/[^l].*)"
          traefik.web.frontend.redirect.replacement: "https://{{ BITBUCKET_REPO_SLUG }}.erp.co.ua"
          traefik.web.port: "8069"
          traefik.web.frontend.entryPoints: "https"
      when: WITH_TEST_DB is undefined or WITH_TEST_DB != "yes"

    - name: Setup production traefik v2 labels
      set_fact:
        production_traefik_v2_labels:
          - key: "traefik.http.middlewares.{{ service }}-web-redirect.redirectregex.regex"
            value: "^(https://{{ BITBUCKET_REPO_SLUG }}.erp.co.ua/website/tests|https://{{ BITBUCKET_REPO_SLUG }}.erp.co.ua/website/info|https://{{ BITBUCKET_REPO_SLUG }}.erp.co.ua/web/database/[^l].*)"
          - key: "traefik.http.middlewares.{{ service }}-web-redirect.redirectregex.replacement"
            value: "https://{{ BITBUCKET_REPO_SLUG }}.erp.co.ua"
          - key: "traefik.http.routers.{{ service }}-web.rule"
            value: "Host(`{{ BITBUCKET_REPO_SLUG }}.erp.co.ua`)"
          - key: "traefik.http.routers.{{ service }}-web.middlewares"
            value: "{{ service }}-web-redirect@docker,fw-proto@file,gzip@file"
          - key: "traefik.http.routers.{{ service }}-web.service"
            value: "{{ service }}-web"
          - key: "traefik.http.routers.{{ service }}-web.entryPoints"
            value: "websecure"
          - key: "traefik.http.services.{{ service }}-web.loadbalancer.server.port"
            value: "8069"
      when: WITH_TEST_DB is undefined or WITH_TEST_DB != "yes"

    - name: Setup custom domain traefik v1 labels
      set_fact:
        domain_traefik_v1_labels:
          traefik.webdom.frontend.rule: "Host:{{DOMAIN}}"
          traefik.webdom.frontend.redirect.regex: "^(https://{{DOMAIN}}/website/tests|https://{{DOMAIN}}/website/info|https://{{DOMAIN}}/web/database/[^l].*)"
          traefik.webdom.frontend.redirect.replacement: "https://{{DOMAIN}}/"
          traefik.webdom.port: "8069"
          traefik.webdom.frontend.entryPoints: "https"
      when: (WITH_TEST_DB is undefined or WITH_TEST_DB != "yes") and DOMAIN is defined and DOMAIN != ""

    - name: Setup custom domain traefik v2 labels
      set_fact:
        domain_traefik_v2_labels:
          - key: "traefik.http.middlewares.{{ service }}-webdom-redirect.redirectregex.regex"
            value: "^(https://{{DOMAIN}}/website/tests|https://{{DOMAIN}}/website/info|https://{{DOMAIN}}/web/database/[^l].*)"
          - key: "traefik.http.middlewares.{{ service }}-webdom-redirect.redirectregex.replacement"
            value: "https://{{DOMAIN}}/"
          - key: "traefik.http.routers.{{ service }}-webdom.rule"
            value: "Host(`{{DOMAIN}}`)"
          - key: "traefik.http.routers.{{ service }}-webdom.middlewares"
            value: "{{ service }}-webdom-redirect@docker,fw-proto@file,gzip@file"
          - key: "traefik.http.routers.{{ service }}-webdom.service"
            value: "{{ service }}-webdom"
          - key: "traefik.http.routers.{{ service }}-webdom.entryPoints"
            value: "websecure"
          - key: "traefik.http.services.{{ service }}-webdom.loadbalancer.server.port"
            value: "8069"
      when: (WITH_TEST_DB is undefined or WITH_TEST_DB != "yes") and DOMAIN is defined and DOMAIN != ""

    - name: Setup naked domain redirect traefik v1 labels
      set_fact:
        naked_domain_traefik_v1_labels:
          traefik.webnakeddom.frontend.rule: "Host:{{NAKED_DOMAIN}}"
          traefik.webnakeddom.frontend.redirect.regex: "^https://{{NAKED_DOMAIN}}/(.*)"
          traefik.webnakeddom.frontend.redirect.replacement: "https://{{DOMAIN}}/$1"
          traefik.webnakeddom.port: "8069"
          traefik.webnakeddom.frontend.entryPoints: "https"
      when: (WITH_TEST_DB is undefined or WITH_TEST_DB != "yes") and DOMAIN is defined and DOMAIN != "" and NAKED_DOMAIN is defined and NAKED_DOMAIN != ""

    - name: Setup naked domain traefik v2 labels
      set_fact:
        naked_domain_traefik_v2_labels:
          - key: "traefik.http.middlewares.{{ service }}-webnakeddom-redirect.redirectregex.regex"
            value: "^https://{{NAKED_DOMAIN}}/(.*)"
          - key: "traefik.http.middlewares.{{ service }}-webnakeddom-redirect.redirectregex.replacement"
            value: "https://{{DOMAIN}}/$1"
          - key: "traefik.http.routers.{{ service }}-webnakeddom.rule"
            value: "Host(`{{NAKED_DOMAIN}}`)"
          - key: "traefik.http.routers.{{ service }}-webnakeddom.middlewares"
            value: "{{ service }}-webnakeddom-redirect@docker,fw-proto@file,gzip@file"
          - key: "traefik.http.routers.{{ service }}-webnakeddom.service"
            value: "{{ service }}-webnakeddom"
          - key: "traefik.http.routers.{{ service }}-webnakeddom.entryPoints"
            value: "websecure"
          - key: "traefik.http.services.{{ service }}-webnakeddom.loadbalancer.server.port"
            value: "8069"
      when: (WITH_TEST_DB is undefined or WITH_TEST_DB != "yes") and DOMAIN is defined and DOMAIN != "" and NAKED_DOMAIN is defined and NAKED_DOMAIN != ""

    - name: Setup all traefik labels
      set_fact: >-
        traefik_labels="{{
          common_labels
          | combine(traefik_v1_labels | default({}))
          | combine(staging_traefik_v1_labels | default({}))
          | combine(staging_traefik_v2_labels | default([]) | items2dict)
          | combine(production_traefik_v1_labels | default({}))
          | combine(production_traefik_v2_labels | default([]) | items2dict)
          | combine(domain_traefik_v1_labels | default({}))
          | combine(domain_traefik_v2_labels | default([]) | items2dict)
          | combine(naked_domain_traefik_v1_labels | default({}))
          | combine(naked_domain_traefik_v2_labels | default([]) | items2dict)
        }}"

    - name: Deploy Odoo Service
      community.docker.docker_swarm_service:
        use_ssh_client: yes
        name: "{{ service }}"
        image: "{{ image }}"
        hostname: "{{ service }}"
        replicas: "{{ replicas }}"
        tty: yes
        init: no
        resolve_image: yes
        endpoint_mode: vip
        networks:
          - "erpunet"
        secrets:
          - secret_name: gcp-service-account.json
        mounts:
          - source: "{{ volume_path }}"
            target: "/var/lib/odoo"
            type: bind
          - source: "/swarm/gv1/geoip"
            target: "/usr/share/GeoIP"
            type: bind
        update_config:
          parallelism: 1
          delay: 15s
          order: stop-first
        labels:
          "{{ traefik_labels }}"
